name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://blog.shrivarshapoojary.in/index.xml"
          max_post_count: 5
          template: "- [$title]($url)"
          committer_username: "blog-post-bot"
          committer_email: "blog-post-bot@example.com"
          commit_message: "Updated with the latest blog posts"